/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example.ticket.booking;

import org.example.ticket.booking.Service.UserBookingService;
import org.example.ticket.booking.entities.Train;
import org.example.ticket.booking.entities.User;
import org.example.ticket.booking.util.UserServiceUtil;

import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;
import java.util.UUID;

public class App {

    public static void main(String[] args) {

        System.out.println("Train Booking System");
        Scanner scanner = new Scanner(System.in);

        int option=0;
        UserBookingService userBookingService;
        try{
            userBookingService =new UserBookingService();
        }catch(Exception e){
           e.printStackTrace();
            return;
        }
        while(option!=7){
            System.out.println("Please enter your option:");
            System.out.println("1. Create a new user");
            System.out.println("2. login user");
            System.out.println("3. Fetch Booking data");
            System.out.println("4. Search Train");
            System.out.println("5. Book a seat");
            System.out.println("6. Cancel my booking");
            System.out.println("7. Exit");
            option=scanner.nextInt();
            scanner.nextLine();

            switch(option){
                case 1:
                    System.out.println("please enter your Name");
                    String name=scanner.nextLine();
                    System.out.println("please enter your Password");
                    String password=scanner.nextLine();
                    User usertoSignup =new User(name,password,
                            UserServiceUtil.hashPassword(password),
                            new ArrayList<>(), UUID.randomUUID().toString().toUpperCase());
                    userBookingService.signUp(usertoSignup);
                    break;

                case 2:
                    System.out.println("please enter your Name");
                    String name1=scanner.nextLine();
                    System.out.println("please enter your Password");
                    String password1=scanner.nextLine();
                    User userToLogin = new User(name1,password1);
                    try{

                        userBookingService = new UserBookingService(userToLogin);
                        userBookingService.loginUser();
                    }catch(Exception e){
                       e.printStackTrace();
                    }
                    break;

                case 3:

                    System.out.println("Fetch Booking data");
                    userBookingService.fetchBooking();
                    break;

                case 4:
                    System.out.println("Search Train");
                    System.out.println("Enter your Source station");
                    String source=scanner.nextLine();
                    System.out.println("Enter your Destination station");
                    String destination=scanner.nextLine();
                    userBookingService.searchAndSelectTrain(source,destination);
                    break;

                case 5:
                    System.out.println("book a seat");
                    userBookingService.bookseat();
                    break;

                case 6:
                    System.out.println("Cancel my booking");
                    Scanner s = new Scanner(System.in);
                    System.out.println("Please enter the TicketID you would like to cancel: ");
                    String ticketId = s.nextLine();
                    userBookingService.cancelBooking(ticketId);

                    break;

                case 7:
                    System.out.println("Exiting Application ........");
                    return;







            }
        }

    }
}
